### PR TITLE
refactor telemetry implementation in sherlock

### PR DESCRIPTION
**Pull request by samuelstroschein**
Closes https://github.com/opral/inlang-sdk/issues/177. 

**Changes**

- uses the build script to define env variables (as already done in the error service) 
  - avoids dependencies on `@inlang/env-variables` which will make contributions much easier. sherlock can soon be developed with doppler 
  - reduces coordination overhead. 

**testing**

- [x] development projects opens
- [x] telemetry events are send to posthog
- [] tests passing not all but that seems unrelated to the telemetry stuff

### CODE REVIEW

**Comment by samuelstroschein** [comment]
@felixhaeberle if you approve. merge

**Comment by felixhaeberle** [comment]
@samuelstroschein can you merge latest `lix-integration`?

**Comment by samuelstroschein** [comment]
@felixhaeberle on it! 🫡

**Comment by samuelstroschein** [comment]
merged in https://github.com/opral/monorepo/commit/dfde8093db1cc7176e2e90aa9056f1876abff27d because the rebase/merge here went wrong

**Pull request closed without merging**
