### PR TITLE
Adds the inlang-plugin-xcstrings plugin to the registry

### PR DESCRIPTION
**Pull request by LukasHechenberger**
Let me know if something is missing :)

### CODE REVIEW

**Comment by LukasHechenberger** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by samuelstroschein** [comment]
Omg @LukasHechenberger you made my day. You are the first external plugin author <3

1. How was the plugin authoring experience?
2. @NilsJacobsen is on vacation till Tuesday. i put him in review, he is responsible for inlang.com and will merge or request changes

**Comment by LukasHechenberger** [comment]
@samuelstroschein Haha, nice :)

We just recently started using inlang in my [QRcard](https://www.qrcardapp.com) app, and I love it so far. The integration into SvelteKit (for the docs), Next.js (for a PAAS we're currently developing), and the app itself (uses react-i18next) worked flawlessly.

We're also developing native extensions for iOS, hence this plugin, and Android, for which I'll write an inlang plugin soon :) Being able to use all these different frameworks with the same translation platform is just a HUGE improvement.

Developing the plugin was really straightforward, thanks to how good your documentation is, thanks for that.

I had some minor issues while developing the marketplace integration though:

- First of all, I initially thought I should add `@inlang/sdk` as a _peerDependency_ to my plugin as probably all plugins depend on it and also tried to add `@sinclair/typebox` as a _dependency_.

  This worked fine as long as I used `inlang module build`, as it uses `bundle: true` in the esbuild options. I switched to use _tsup_ later because I could not figure out how to generate type declarations for the plugin using the inlang CLI.

  This caused plugin errors inside fink, as it expects all dependencies to be bundled (or at least I think so?). Removing the peer dependency on `@inlang/sdk` and bundling `@sinclair/typebox` by moving it to _devDependencies_ worked out fine. I just think it might be a good idea to **mention all dependencies have to be bundled in the docs**.

- Most of the info I added to the _marketplace-manifest.json_ is also present in _package.json_, therefore I used a script[^1] to generate it from a _marketplace-manifest.template.json_ - which currently only contains the `displayName` property. I think most plugin authors will have a package.json, so you could try to infer all those manifest properties from a plugin's _package.json_ anyway.
- I had hoped to see a preview of how my plugin would look on the marketplace before it's published. Just to make sure the readme blends in with the rest of the documentation, and also to see how the [custom HTML elements](https://inlang.com/documentation/sdk/publish-to-marketplace#custom-web-components) look like. That's the reason I did not use them in my readme so far.
- The `inlang module init` command creates a _package.json_ file that contains `workspace:*` dependencies on `@inlang/sdk` etc., which obviously do not work in other (mono)repos. The fix was easy, but someone with less experience in developing npm/pnpm packages may have some struggles.
- Also, somewhat unrelated: While developing, I tried to use your VSCode extension to test the plugin on a real project (which is QRcard). I was not able to find out how to view the logs. Debugging was basically "either you see an error right away, or it probably worked." Issues inside `saveMessage` calls are completely ignored, or at least I was not able to find out what went wrong from within my VSCode project.

**Please don't feel offended by all my comments, I still really like your work and will continue contributing.** Let me know if there is something particular I can help you with!

I will open-source my plugin repository later so you can see my full setup if you need to.

[^1]: _./scripts/sync-manifests.mjs_

    ```javascript
    import { readFile, writeFile } from 'fs/promises';

    async function readJson(path) {
      return JSON.parse(await readFile(path, 'utf8'));
    }

    async function syncManifests() {
      const npmManifest = await readJson('./package.json');
      const inlangManifest = await readJson('./marketplace-manifest.template.json');
      const { id } = (await import(`../${npmManifest.module}`)).default;

      const jsdelivrLink = (path) =>
        new URL(path, `https://cdn.jsdelivr.net/npm/${npmManifest.name}@latest/`);

      inlangManifest.id = id;
      inlangManifest.description = { en: npmManifest.description };
      inlangManifest.keywords = npmManifest.keywords;
      inlangManifest.license = npmManifest.license;
      inlangManifest.module = jsdelivrLink(npmManifest.module);
      inlangManifest.readme = jsdelivrLink('README.md');
      inlangManifest.publisherName = 'Hechenbros';

      await writeFile(
        './marketplace-manifest.json',
        `${JSON.stringify(inlangManifest, null, 2)}\n`,
      );
    }

    syncManifests().catch((error) => {
      console.error(error);
      process.exitCode = 1;
    });
    ```

**Comment by samuelstroschein** [comment]
Now you made my day twice! Thanks for the elaborate feedback!

> Please don't feel offended by all my comments, I still really like your work and will continue contributing. Let me know if there is something particular I can help you with!

Oh, don't worry haha! We are all very direct in the team. No offense taken!

> Being able to use all these different frameworks with the same translation platform is just a HUGE improvement

What app are you referring to with translation platform? [Fink](https://inlang.com/m/tdozzpar/app-inlang-finkLocalizationEditor)?

> This worked fine as long as I used inlang module build, as it uses bundle: true in the esbuild options. I switched to use tsup later because I could not figure out how to generate type declarations for the plugin using the inlang CLI.

Why did you want to generate type declarations for the plugin? 

The idea behind `inlang module build` was that developers don't have to think about "how to build this correctly for inlang". Mentioning that everything needs to be bundled on the docs seems redundant if you wouldn't have had the desire to ditch `inlang module build`. 

> I think most plugin authors will have a package.json, so you could try to infer all those manifest properties from a plugin's package.json anyway.

Maybe but we won't use NPM as the registry in the long run and, therefore, don't want a dependency on NPM. 

> I had hoped to see a preview of how my plugin would look on the marketplace before it's published. Just to make sure the readme blends in with the rest of the documentation, and also to see how the [custom HTML elements](https://inlang.com/documentation/sdk/publish-to-marketplace#custom-web-components) look like. That's the reason I did not use them in my readme so far.

Yep. We discussed this. A preview in writing the documentation would be extremely helpful. We likely have something brand new in mind which will be vastly superior to Markdown (internal name is papier). Dependent on how long we need to build papier and dependencies, we might skip the markdown stuff soon. 

> he inlang module init command creates a package.json file that contains workspace:* dependencies 

Bug filed https://github.com/opral/inlang-cli/issues/7

**Comment by NilsJacobsen** [comment]
Hey @LukasHechenberger I'll do the review today. Thanks so much for your contribution 🔥

**Comment by NilsJacobsen** [comment]
It looks great. I only have a small remark. The `readme` prop in the manifest is deprecated. Please use `pages`. By doing that, you can also link the changelog.

```json
{
  "$schema": "https://inlang.com/schema/marketplace-manifest",
  "displayName": {
    "en": "Xcode String Catalogs" 
  },
  "publisherIcon": "https://hechenbros.com/favicon.png",
  "id": "plugin.hechenbros.xcstrings",
  "description": {
    "en": "An inlang plugin to handle Xcode String Catalogs"
  },
  "keywords": [
    "inlang",
    "plugin",
    "xcstrings",
    "xcode",
    "translation",
    "ios",
    "mac"
  ],
  "license": "MIT",
  "module": "https://cdn.jsdelivr.net/npm/inlang-plugin-xcstrings@latest/out/index.js",
- "readme": "https://cdn.jsdelivr.net/npm/inlang-plugin-xcstrings@latest/README.md", 
  "pages": {
    "/": "https://cdn.jsdelivr.net/npm/inlang-plugin-xcstrings@latest/README.md",
    "/changelog": "https://cdn.jsdelivr.net/npm/inlang-plugin-xcstrings@latest/CHANGELOG.md"
  }
  "publisherName": "Hechenbros"
}
```

**Comment by LukasHechenberger** [comment]
Hm, I didn't find the `pages` property anywhere in the documentation 😅

I added it just as you suggested but kept the `readme` prop as well, I hope that's fine.

**Comment by NilsJacobsen** [comment]
Right, this is brand new. I will update the docs soon.

**Comment by NilsJacobsen** [comment]
@LukasHechenberger 
You could also provide a publisherLink in your manifest, so people can click on your avatar on inlang.com.

```json
{
   "publisherLink": "LINK_TO_YOUR_GITHUB"
}
```

**Pull request merged**
