### PR TITLE
Fink-lazy-lix-support

### PR DESCRIPTION
**Pull request by NiklasBuchfink**
This should fix:
- https://linear.app/opral/issue/FINK-31/fork-status-breaks-loading-fink-with-lazy-loading
- https://linear.app/opral/issue/FINK-32/branch-menu-needs-to-be-lazy-to-suppport-new-lazy-lix

### CODE REVIEW

**Comment by NiklasBuchfink** [comment]
@janfjohannes Let me know if that's what you had in mind. I will continue on Wednesday and implement your suggestions.

**Comment by janfjohannes** [comment]
@NiklasBuchfink  tbh i dont really understand what you are doing :D those are two different tickets that you seem to mixup.  
the idle callback idea was for the fork sync not the brnches. for branches the described action should be triggered on opening the menu, but also not change the render source for the branches. if you need more clarification lets hop on a call....

**Review by janfjohannes — CHANGES_REQUESTED** [review]
see comment

**Review by janfjohannes — APPROVED** [review]
great, sorry for the confusion, my error

**Comment by janfjohannes** [comment]
@NiklasBuchfink  i am merging this as i need it to continue.

**Pull request merged**
