### PR TITLE
SHERL-17: fix preferredLanguageTag wrong auto selection in Sherlock 🕵️‍♂️

### PR DESCRIPTION
**Pull request by felixhaeberle**
This PR aims to fix https://linear.app/opral/issue/SHERL-17/[bug]-incorrect-error-message-when-sherlock-preferred-language-is-set

### CODE REVIEW

**Review by jldec — CHANGES_REQUESTED** [review]
@felixhaeberle I'm still seeing the same issue as reported.

- set sherlock preview language to `de` in a project which has `de`
- open a project with only `en`
- look for the preview of any message in a code file

The statusbar reports `en`, but the message previews still report errors.

Screenshot 2024-04-09 at 17 55 10

**Comment by felixhaeberle** [comment]
I'll investigate once more. I guess there are two issues involved here. First is already fixed -> Fallback to source language if preferredLanguageTag isn't in project. Second will be to fix the message (first find out why it is appearing).

**Comment by jldec** [comment]
> I'll investigate once more. I guess there are two issues involved here. First is already fixed -> Fallback to source language if VS code setting of preferredLanguageTag isn't in project. Second will be to fix the message (first find out why it is appearing).

The "preferred" language tag logic added to [statusBar.ts](https://github.com/opral/monorepo/pull/2537/files#diff-f2e67eeb4eb388c215c948eade3e27446b2455e9c070875ec474f2c16c99cb3bR37-R39) needs to be extracted and used in [messagePreview.ts](https://github.com/opral/monorepo/blob/b25aaab3e0eff19d83ed36d419cc25ea06686d56/inlang/source-code/ide-extension/src/decorations/messagePreview.ts#L55) also.

**Comment by felixhaeberle** [comment]
@jldec Watch this LOOM :)
https://www.loom.com/share/f4cc4bb7d7454035937d96c1a4122c03

**Review by jldec — APPROVED** [review]
works for me now - thanks @felixhaeberle

**Pull request merged**
