### PR TITLE
t function matcher extract message should offer no brackets version | Sherlock 🕵️‍♂️

### PR DESCRIPTION
**Pull request by felixhaeberle**
- fix SHERL-64
cc @KraXen72

### CODE REVIEW

**Comment by KraXen72** [comment]
thanks! might i suggest wrapping the last option in a set of double quotes? because after extraction, the entire thing, including quotes gets replaced, so with the last option, it would mean you have to re-add the quotes manually

**Comment by felixhaeberle** [comment]
@KraXen72 Can you make an exmaple where this would be helpful? The last option is only to have the messageId ready to copy if you use another format.

**Comment by KraXen72** [comment]
<Text text="whatever" />
1. extract it, type message_id
2. change text attribute to tx as per my custom components

current:
<Text tx=message_id /> (invalid js, have to add " around it manually

proposed:
<Text tx="message_id" /> (valid js, ready to go without more changes)

**Comment by felixhaeberle** [comment]
Then just extract `whatever ` without quotes?

**Pull request merged**
