### PR TITLE
adds reactivity to aliases again

### PR DESCRIPTION
**Pull request by martin-lysk**
This PR reintroduces reactivtiy to aliases for messages (experimental feature - as requested via https://linear.app/opral/issue/MESDK-94) again

### CODE REVIEW

**Comment by jldec** [comment]
Thanks @martin-lysk - I did a quick test pass with this branch. 

- 2 sdk loadProject query tests are failing. 
- Alias behavior in Sherlock appears to be fixed. 👍 
Screenshot 2024-06-06 at 17 55 09

**Comment by martin-lysk** [comment]
Thanks for the ping @jldec tests fixed, changelog added - can't reproduce how the they ended up green on my device guess some strange caching. How did people sleep without CI ;-) .

**Review by jldec — APPROVED** [review]
LGTM
b.t.w. it would be nice to have a test for getByDefaultAlias() after initial load (we have one for after createMessage) I think that would have caught this bug. Up to you if you think it's worth adding.

**Review by felixhaeberle — APPROVED** [review]
lgtm 👍

**Pull request merged**
