### PR TITLE
create lint rules to replace missing inlang sdk / lix functionality

### PR DESCRIPTION
**Pull request by felixhaeberle**
cc SHERL-108

### CODE REVIEW

**Comment by felixhaeberle** [comment]
@samuelstroschein can you verify the behavior?

**Comment by samuelstroschein** [comment]
Looks correct. Two suggestions: 

1. Avoid calling global state. Your tests are becoming complex. If you don't use `state()` by passing the project into the function you avoid mocking.  

```diff
-export const missingMessage = async (bundleId: string): Promise<LintResult[]> => {
-	const db = state().project.db
-	const locales = (await state().project.settings.get()).locales
+export const missingMessage = async (bundleId: string, project: InlangProject): Promise<LintResult[]> => {
+      const locales = (await project.settings.get()).locales

	const bundle = await selectBundleNested(db).where("bundle.id", "=", bundleId).executeTakeFirst()

	if (!bundle) return []

	// Check if for every locales defined in the settings, ther is a message with a corresponding locale

	const bundleWithMissingMessage = bundle.messages.filter((message) => {
		return !locales.includes(message.locale) || message.variants.length === 0
	})

	return bundleWithMissingMessage.map((message: any) => ({
		bundleId: bundle.id,
		messageId: message.id,
		messageLocale: message.locale,
		code: "missingMessage",
		description: `Message with locale ${message.locale} is missing the bundle with id ${bundle.id}`,
	}))
}
```

Your tests become simpler. Instead of calling vitest to mock your `state()` thing, you can directly test the function by passing a fresh in memory project. 

```ts
	it("should return missing messages if no messages for some locales or variants are empty", async () => {
               // no need to mock the project if you create a new in memory project
	       const project = await loadProjectInMemory({ blob: await newProject() })

                await insertBundleNested(mockBundle, project.db)	

		const result = await missingMessage("bundle1", project)
		expect(result).toEqual<LintResult[]>([
			{
				bundleId: "bundle1",
				messageId: "msg1",
				messageLocale: "en",
				code: "missingMessage",
				description: "Message with locale en is missing the bundle with id bundle1",
			},
		])
	})

```


2. Even if you want to keep mocking global state (i highly recommend against it), your live becomes easier if you create fresh projects for each tests (testing lix file formats is so easy!) 

```diff
vi.mock("../state.js", () => ({
	state: () => ({
-		project: {
-			db: {},
-			settings: {
-				get: vi.fn(() =>
-					Promise.resolve({
-						locales: ["en", "fr"],
-						baseLocale: "en",
-					})
-				),
-			},
-		},
+             project: await loadProjectInMemory({ blob: await newProject() })
	}),
}))
```

**Review by samuelstroschein — COMMENTED** [review]
Looks correct. Two suggestions: 

1. Avoid calling global state. Your tests are becoming complex. If you don't use `state()` by passing the project into the function you avoid mocking.  

```diff
-export const missingMessage = async (bundleId: string): Promise<LintResult[]> => {
-	const db = state().project.db
-	const locales = (await state().project.settings.get()).locales
+export const missingMessage = async (bundleId: string, project: InlangProject): Promise<LintResult[]> => {
+      const locales = (await project.settings.get()).locales

	const bundle = await selectBundleNested(db).where("bundle.id", "=", bundleId).executeTakeFirst()

	if (!bundle) return []

	// Check if for every locales defined in the settings, ther is a message with a corresponding locale

	const bundleWithMissingMessage = bundle.messages.filter((message) => {
		return !locales.includes(message.locale) || message.variants.length === 0
	})

	return bundleWithMissingMessage.map((message: any) => ({
		bundleId: bundle.id,
		messageId: message.id,
		messageLocale: message.locale,
		code: "missingMessage",
		description: `Message with locale ${message.locale} is missing the bundle with id ${bundle.id}`,
	}))
}
```

Your tests become simpler. Instead of calling vitest to mock your `state()` thing, you can directly test the function by passing a fresh in memory project. 

```ts
	it("should return missing messages if no messages for some locales or variants are empty", async () => {
               // no need to mock the project if you create a new in memory project
	       const project = await loadProjectInMemory({ blob: await newProject() })

                await insertBundleNested(mockBundle, project.db)	

		const result = await missingMessage("bundle1", project)
		expect(result).toEqual<LintResult[]>([
			{
				bundleId: "bundle1",
				messageId: "msg1",
				messageLocale: "en",
				code: "missingMessage",
				description: "Message with locale en is missing the bundle with id bundle1",
			},
		])
	})

```


2. Even if you want to keep mocking global state (i highly recommend against it), your life becomes easier if you create fresh projects for each tests (testing lix file formats is so easy!) 

```diff
vi.mock("../state.js", () => ({
	state: () => ({
-		project: {
-			db: {},
-			settings: {
-				get: vi.fn(() =>
-					Promise.resolve({
-						locales: ["en", "fr"],
-						baseLocale: "en",
-					})
-				),
-			},
-		},
+             project: await loadProjectInMemory({ blob: await newProject() })
	}),
}))
```

**Comment by felixhaeberle** [comment]
thanks for the review! will implement the suggestions as part of the [missing link because linear is down. linking github instead](https://github.com/opral/inlang-sherlock/issues/96) task where I'm going to integrate the lint rules

**Pull request merged**
