### PR TITLE
add: `change.operation`

### PR DESCRIPTION
**Pull request by samuelstroschein**
## Context

Apps can't know if a change was an insert, update, or a delete. This is a follow up of https://github.com/opral/monorepo/pull/3043. 

## Proposal 

Expose the `operation` information that differs provide in a change. Apps will be able to display if a change was/is an insert, update, or deletion.  

```diff

export type Change = {
	id: string
	file_id: LixFile["id"]
	commit_id?: Commit["id"]
	plugin_key: LixPlugin["key"]
+	operation: "insert" | "update" | "delete"
	type: string
	value?: 
	meta?: string // JSONB
}


```

## Additional information

Testing with finkv2 indicates that everything works as expected. However, the written unit test is failing because the query `await lix.selectFrom("changes")` doesn't resolve. Don't know why. Works in fink.

### CODE REVIEW

**Review by janfjohannes — CHANGES_REQUESTED** [review]
i expect this is what the meta field is for, no need to add this as new field. especially as the workding insert update delete is sql lingo and only makes sense for inlang as that uses sqlite, but other file formats might have different operations.

**Comment by samuelstroschein** [comment]
@janfjohannes Can you give examples of more operations that are needed to model change conflicts? 

I think you refer to collisions that should happen based on two update "operations" e.g. if the drill size changed, and someone else changed the drill size, that should raise a change conflict. Those are still two "update" operations, though. Modeling the drill size changed change conflict would happen as so: 

```ts
if (old.drillSize !== neu.drillSize){
  changeConflicts.push("Drill size differed. Choose one.", fixes: [])
}
```

There is no need to express "drill size changed" as part of the operation [given that we store snapshots]. 

**Reasons for the operation first class prop**

- the operations 'insert', 'update','delete' and contained types seems universal across any file given that we store snapshots. 
- lix (via the host) and lix apps need awareness if something has been inserted, updated, or deleted to render the correct diffs
- without the operation information, working with `change.value` is cumbersome because it's always potentially undefined. a check with `if (change.operation !== "deletion")` to derive that `change.value` exists is not possible.


Examples of universality:

- inlang: insertion, update, deletion of bundle, message, variant, settings
- source code: insertion, update, deletion of a line 
- semantic soure code: insertion, update, deletion of a function, variable, class, etc.
- markdown: insertion, update, deletion of a paragraph, word, ...
- cad: insertion, update, deletion of component
- figma: insertion, update, deletion of layer, frame, component, vector, ...

**Comment by janfjohannes** [comment]
@samuelstroschein  insert is allready an example that makes no sense outside sql, you inssert into a table but you would otherwise create an id or a document etc. other formats might have move, rename, change size etc. 

can you give a reason why this cannot be put into meta?

**Comment by samuelstroschein** [comment]
I'll build a prototype that contains the operation field in `meta` to see how good/bad that works. Will report later today.  

> can you give a reason why this cannot be put into meta?

Hmm. I assumed that lix itself, the latest with the host, needs to know if something is a create, update, or delete operation. Otherwise, diffing becomes complicated due to the implicit meaning of create, update, and delete, which might run out of sync with a plugin's understanding of create, update, delete. Lix current implicit definition: 

- `create` = if (change.parent_id === undefined && value)
- `update` =  if (change.parent_id && value)
- `delete` =  if (change.parent_id && value === undefined) 

Communicating this will lead to complicated docs, and surely to downstream bugs because the implicitness will lead to a situation where lix treats something as X while the plugin had a different intent:

```ts
change = {
  parent_id: "53239jsfsfs",
  value: undefined, // <- undefined is implicitly treated by lix as deletion (will lead to a bug)
  meta: {
    "operation": "create"
  }
}

```

Furthermore, working with changes becomes complicated because 

> you inssert into a table but you would otherwise create

It doesn't matter if we name it `create, update, delete` or `insert, update, delete`. I can rename it to `create` instead of `insert`.

> other formats might have move, rename, change size etc.

This seems to be all updates of the provided snapshot. The semantic meaning "move," "rename," or "change size" might be meta information that a plugin/app saves to avoid a diff, but the data was updated regardless of whether it was moved, renamed, or whatever. Most importantly, the semantic understanding can be reconstructed from the snapshots. 

```ts
function wasRenamed(old, neu){
 return old.name !== neu.name
}
```

```ts
function sizeChanges(old, neu){
  if (old.size !== neu.size){}
}
```

**Review by janfjohannes — APPROVED** [review]

**Pull request merged**
