### PR TITLE
support fink repo permisision detections

### PR DESCRIPTION
**Pull request by janfjohannes**
support fink repo permisision detections

### CODE REVIEW

**Comment by janfjohannes** [comment]
await repo.getMeta() will allow you to detect if:

- forking is allowed, if not hide the fork feature
- user has admin rights  permissions.admin, if not and app not installed, disable push and tell user to have admin install app
- if pull permission is false and allow forking is true only show the forking workflow

**Comment by janfjohannes** [comment]
update:
@NiklasBuchfink  you now also have an isInstalled boolean in the getmeta object to see if the app is installed. this should give you all information you need!

**Review by NiklasBuchfink — APPROVED** [review]
Should we change "allow_forking" to "allowForking"?

Everything else looks good, I will implement it tomorrow 👍

**Comment by janfjohannes** [comment]
@NiklasBuchfink  i changed it. also i dont think logout on permission change is needed anymore, i hope i just did  a mistake while testing but lets keep an eye for inconsistent behaviour

**Pull request merged**
