### PR TITLE
Support SolidStart Beta 2 for paraglide adapter

### PR DESCRIPTION
**Pull request by thetarnav**
Support SolidStart Beta 2. (`@solidjs/start@0.4` and `@solidjs/router@0.10`)

Renames `languageTagInPathname` to `languageTagFromPathname`

Replaces `useLocationLanguageTag` with `useLocationPathname`

`translateHref` doesn't take `source_language_tag` param anymore

Fixes the issue with german characters not showing up properly with SSR. (must have been a solidstart beta 1 issue)

Adds an example of how to add alternate links to head.

The solidstart build breaks right now, so we might have to wait before merging. It's a known issue and nothing related to paraglide I think.

```bash
vite v4.5.0 building SSR bundle for production...
✓ 21 modules transformed.
✓ built in 486ms
[commonjs--resolver] Missing "./web/storage" specifier in "solid-js" package

 ERROR  Missing "./web/storage" specifier in "solid-js" package
```

The paraglide vite plugin also doesn't work now.

```bash
/home/thetarnav/inlang/inlang/source-code/paraglide/paraglide-js/dist/index.js:8006
var gitOrigin = parseOrigin({ remotes: await getGitRemotes() });var posthog3 = new _posthogNode.PostHog(publicEnv.PUBLIC_POSTHOG_TOKEN ?? "placeholder", { host: "https://eu.posthog.com", // Events are not captured if not immediately flushed.
                                             ^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (node:vm:94:7)
    at createScript (node:vm:250:10)
    at Object.runInThisContext (node:vm:298:10)
    at evalModule (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256254)
    at jiti (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
    at /home/thetarnav/inlang/inlang/source-code/paraglide/paraglide-js-adapter-unplugin/dist/index.js:5:17
    at evalModule (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
    at /home/thetarnav/inlang/inlang/source-code/paraglide/paraglide-js-adapter-vite/dist/index.js:1:199
    at evalModule (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
    at jiti (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
    at /home/thetarnav/inlang/inlang/source-code/paraglide/paraglide-js-adapter-solidstart/example/vite.config.ts:2:31
    at evalModule (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:256443)
    at Object.jiti (/home/thetarnav/inlang/node_modules/.pnpm/jiti@1.21.0/node_modules/jiti/dist/jiti.js:1:254371)
    at resolveConfig (file:///home/thetarnav/inlang/node_modules/.pnpm/c12@1.5.1/node_modules/c12/dist/index.mjs:288:24)
    at loadConfig (file:///home/thetarnav/inlang/node_modules/.pnpm/c12@1.5.1/node_modules/c12/dist/index.mjs:116:40)
    at loadApp (file:///home/thetarnav/inlang/node_modules/.pnpm/vinxi@0.0.52_@types+node@20.10.4/node_modules/vinxi/lib/load-app.js:35:29)
    at async FSWatcher.<anonymous> (file:///home/thetarnav/inlang/node_modules/.pnpm/vinxi@0.0.52_@types+node@20.10.4/node_modules/vinxi/bin/cli.mjs:81:22)
```

ping @LorisSigrist

### CODE REVIEW

**Comment by LorisSigrist** [comment]
I'll look into paraglide-adapter-vite failing

**Comment by samuelstroschein** [comment]
@LorisSigrist what is the status here?

**Comment by LorisSigrist** [comment]
We were having impossible to debug dependency issues with the example in the monorepo. The adapter works great outside the monorepo. We've now reached the decision to remove the example from the repo for now & merge the adapter code only.

**Comment by samuelstroschein** [comment]
@LorisSigrist can you elaborate on the dependency issues? I'd like to consider them for #2039

**Comment by LorisSigrist** [comment]
The `solid-js` package get's installed in a broken state. There are internal imports that cannot be resolved causing runtime errors for no reason. We tried really hard to debug it, but couldn't reproduce it outside the monorepo. I unfortunately have no idea what's wrong, but we've already spent too much time on it & the adapter works fine, so we decided to have the example outside the monorepo.

**Comment by samuelstroschein** [comment]
so close this?

**Comment by LorisSigrist** [comment]
I'll be removing the example from this branch and merging the changes to the adapter later today, so please don't close it yet.

**Pull request merged**
