### PR TITLE
disable previews in render.yaml

### PR DESCRIPTION
**Pull request by jannesblobel**
disable preview deploys in a PR

### CODE REVIEW

**Comment by jannesblobel** [comment]
@NiklasBuchfink @NilsJacobsen @janfjohannes  
Is anyone using the preview deploy function atm?

**Comment by jannesblobel** [comment]
@NiklasBuchfink, why is Ninja failing here?

**Comment by janfjohannes** [comment]
@jannesblobel  ninja is currently broken, niklas is on it. im not using preview deployments as github login does not work on the domains and without testing login i have no use for it

**Comment by jannesblobel** [comment]
> Member
I haven't found out anything about it. You can make [skip preview] but nothing like run preview or similar.

**Pull request merged**
