### PR TITLE
bump workflows and lockfile to pnpm v9

### PR DESCRIPTION
**Pull request by jldec**
from [discord](https://discord.com/channels/897438559458430986/1234460900904402964) (internal)

The upgrade appears worthwhile
https://github.com/pnpm/pnpm/releases/tag/v9.0.0
> Lockfile v9 is adopted. This new format has changes for better readability, and better resistence to Git conflicts.

### CODE REVIEW

**Comment by jldec** [comment]
@felixhaeberle 
I switched this PR to draft because CI is still using pnpm v8
Should we just ship it yolo - or is there a way to test PR with PR workflows?

Screenshot 2024-04-29 at 17 56 52

**Review by samuelstroschein — APPROVED** [review]
Switching the lock file to v9 seems logical.

**Comment by jldec** [comment]
Darn - missed one - followup PR incoming.
https://github.com/opral/monorepo/blob/ca6ff51bc54aa8a6d4c80e7646fcd002ec9577a2/.github/workflows/continuous-integration.yml#L28

**Comment by jldec** [comment]
https://github.com/opral/monorepo/pull/2680

**Pull request merged**
