### PR TITLE
introduce settings component in Sherlock 🕵️‍♂️

### PR DESCRIPTION
**Pull request by felixhaeberle**
@NilsJacobsen this is your playground for the settings component in sherlock

TODO's:
- [X] bug: can't pass an object easily in HTML, we need some sort of framework to run the lit component in. does lit itself provide a runtime? 

-> we are now ging with serializable props as decided in https://linear.app/opral/issue/INLMC-26/do-the-ui-component-props-need-to-be-serializable

- [x] move out of the sidebar into big window screen
- [x] introduce settings icon to open settings window
- [x] add styling to component

### CODE REVIEW

**Comment by felixhaeberle** [comment]
@NilsJacobsen I removed your assignment until we get the component working in the vs code webview environment inside of a framework we run there, and in this framework we then import the component. 

rn, I tried to use the component as is in HTML which is a bit cumbersome (but was my preferred way up until now)

**Comment by felixhaeberle** [comment]
@opral/inlang-paraglide-js @opral/inlang-fink any ideas why CI is failing? something according to editor & paraglidejs ?

**Comment by NilsJacobsen** [comment]
Thanks for creating it. Gonna have a look.

**Comment by felixhaeberle** [comment]
it still has a problem with settings object passing — would be cool if you can fix this!:)

**Comment by felixhaeberle** [comment]
@NilsJacobsen I assign you until this is fixed from your side (I saw you have another branch open). Please assign back if you are ready and this works.

**Comment by NilsJacobsen** [comment]
No you should be able to use the component as in the html example: https://github.com/opral/monorepo/blob/main/inlang/source-code/settings-component/src/stories/inlang-settings.stories.ts

**Comment by felixhaeberle** [comment]
@NilsJacobsen I updated to lit-html & the new API – can you investigate why this new API isn't working? "No Inlang project found" even tho I pass one in. Thanks!:)

**Comment by NilsJacobsen** [comment]
@felixhaeberle the new api is not merged yet, it is blocked by a lix issue. But thanks for adding lit-html. Gonna have a look when it's ready.

**Comment by felixhaeberle** [comment]
@NilsJacobsen can you link the issue instead of saying "a lix issue"? I also looked in your draft PR and can't find a link.


offtopic: is the ease of linking gone now with app switching between github&linear ?

**Comment by NilsJacobsen** [comment]
I guess the problem is that this PR is not linked in linear. 
Lix issue: https://linear.app/opral/issue/LIX-36/build-error-message-skd-uses-node-specific-import

**Comment by felixhaeberle** [comment]
@NilsJacobsen Did you see my [latest commit](https://github.com/opral/monorepo/pull/2392/commits/b70f67de1a31bd95a5d4d8918d5e773db8ebcdb9)? 
I have now prepared the extension to render the serializable settings and react on the `onSetSettings` (shouldn't this be `onSaveSettings`?) function.

**Comment by NilsJacobsen** [comment]
The current state should work @felixhaeberle. Please create issues for problems you have or foresee.

**Comment by NilsJacobsen** [comment]
@felixhaeberle I tested the updating of state in the ide-extension. I tried to add a language, and it worked fine 🙏.

**Comment by felixhaeberle** [comment]
And you broke my test again haha! No worries I'll take over now and finish this, thank you and have a happy eastern time 🐣

**Pull request merged**
